# MIT License
# 
# Copyright (c) 2024 Jeroen Ooms
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 15 3 *'  # March 15 at noon UTC
    - cron: '0 12 15 6 *'  # June 15 at noon UTC
    - cron: '0 12 15 9 *'  # September 15 at noon UTC
    - cron: '0 12 15 12 *' # December 15 at noon UTC

name: Create Production Snapshot (legacy GitHub Pages version)

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:

      - name: Fetch the latest commit of the Production repository.
        uses: actions/checkout@v4

      - name: Clone Staging universe.
        uses: actions/checkout@v4
        with:
          repository: '${{ github.repository_owner }}/staging'
          path: 'staging'

      - name: Copy important files from Staging.
        run: |
          cp staging/*.txt .
          cp staging/snapshot.* .
      
      - name: Remove local copy of Staging.
        run: rm -rf staging

      - name: Download snapshot.
        run: |
          cat snapshot.url | xargs curl -Lo snapshot.zip
          unzip snapshot.zip && rm -f snapshot.zip

      - name: Push to the gh-pages branch.
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          clean: false
          branch: gh-pages
          folder: .
